import player_class as p

# All players currently avalible to be guessed and their attributes
# currently includes all NU basketball and hockey players from the 
# 2023-24 season plus, and all NU baseball players from the 2023 season
# Also Tyson Walker because I said so
players = [
    p.player("Joe Pridgen", 77, "MBB", "Guard", "Sr", 0),
    p.player("Masai Troutman", 78, "MBB", "Guard", "So", 1),
    p.player("Glen McClintock", 74, "MBB", "Guard", "Sr", 2),
    p.player("Kyle Squires", 80, "MBB", "Guard", "So", 3),
    p.player("Rashad King", 78, "MBB", "Guard", "So", 4),
    p.player("William Kermoury", 77, "MBB", "Guard", "Fr", 8),
    p.player("Luka Sakota", 78, "MBB", "Guard", "Sr", 9),
    p.player("Harold Woods", 77, "MBB", "Guard", "Fr", 10),
    p.player("JB Frankel", 76, "MBB", "Guard", "Fr", 11),
    p.player("Alexander Nwagha", 80, "MBB", "Forward", "Sr", 12),
    p.player("Jared Turner", 80, "MBB", "Guard", "So", 13),
    p.player("Bryce Johnson", 68, "MBB", "Forward", "Sr", 21),
    p.player("Chris Doherty", 79, "MBB", "Forward", "Sr", 33),
    p.player("Collin Metcalf", 81, "MBB", "Forward", "So", 45),

    p.player("Jaelyn Batts", 72, "WBB", "Guard", "Sr", 0),
    p.player("Derin Erdogan", 67, "WBB", "Guard", "Sr", 1),
    p.player("Oralye Kiefer", 75, "WBB", "Forward", "Fr", 11),
    p.player("Camille Clement", 68, "WBB", "Guard", "Jr", 12),
    p.player("Amyrah Sapenter", 68, "WBB", "Guard", "Sr", 14),
    p.player("Yirsey Quéliz", 64, "WBB", "Guard", "Fr", 15),
    p.player("Sophia Carlisle", 75, "WBB", "Forward", "Fr", 20),
    p.player("Ariana Webb", 69, "WBB", "Guard", "So", 21),
    p.player("Maddie Vizza", 66, "WBB", "Guard", "Sr", 22),
    p.player("Gemima Motema", 69, "WBB", "Guard", "Jr", 23),
    p.player("Asha Parker", 74, "WBB", "Forward", "Jr", 24),
    p.player("Deja Bristol", 73, "WBB", "Forward", "Sr", 31),
    p.player("Marian Turnbull", 67, "WBB", "Guard", "So", 32),
    p.player("Halle Idowu", 71, "WBB", "Guard", "Sr", 35),

    p.player("Lily Shannon", 70, "WHKY", "Wing", "So", 2),
    p.player("Taylor Guarino", 65, "WHKY", "Defense", "Jr", 3),
    p.player("Tory Mariano", 69, "WHKY", "Defense", "Jr", 4),
    p.player("Katy Knoll", 67, "WHKY", "Center", "Sr", 6),
    p.player("Molly Griffin", 64, "WHKY", "Wing", "Sr", 8),
    p.player("Kristina Allard", 64, "WHKY", "Defense", "So", 9),
    p.player("Holly Abela", 64, "WHKY", "Wing", "So", 10),
    p.player("Mady Cipolla", 62, "WHKY", "Wing", "Fr", 14),
    p.player("Ellie Mabardy", 63, "WHKY", "Wing", "Fr", 15),
    p.player("Lily Yovetich", 64, "WHKY", "Defense", "Sr", 16),
    p.player("Mia Langolis", 67, "WHKY", "Wing", "So", 17),
    p.player("Becca Vastone", 65, "WHKY", "Wing", "Sr", 18),
    p.player("Abbey Marohn", 67, "WHKY", "Defense", "Sr", 19),
    p.player("Allie Lalonde", 68, "WHKY", "Wing", "Fr", 21),
    p.player("Peyton Compton", 63, "WHKY", "Wing", "Fr", 22),
    p.player("Peyton Cullaton", 67, "WHKY", "Wing", "Sr", 23),
    p.player("Rylie Jones", 66, "WHKY", "Defense", "Fr", 26),
    p.player("Megan Carter", 68, "WHKY", "Defense", "Sr", 27),
    p.player("Paige Taborski", 67, "WHKY", "Goaltender", "Jr", 35),
    p.player("Gwyneth Philips", 67, "WHKY", "Goaltender", "Sr", 37),
    p.player("Jules Constantinople", 65, "WHKY", "Defense", "So", 41),
    p.player("Taze Thompson", 66, "WHKY", "Wing", "Jr", 44),
    p.player("Lily Brazis", 65, "WHKY", "Wing", "So", 61),
    p.player("Mattie Robitzer", 64, "WHKY", "Defense", "Fr", 72),
    p.player("Skylar Irving", 68, "WHKY", "Wing", "Jr", 88),
    p.player("Peyton Anderson", 65, "WHKY", "Wing", "Sr", 91),
    p.player("Avery Anderson", 64, "WHKY", "Wing", "So", 92),
    p.player("Alyssa Antonakis", 66, "WHKY", "Wing", "So", 94),

    p.player("Connor Hopkins", 73, "MHKY", "Goaltender", "Sr", 1),
    p.player("Nolan Hayes", 73, "MHKY", "Defense", "Fr", 3),
    p.player("Pito Walton", 74, "MHKY", "Defense", "Sr", 4),
    p.player("Hunter McDonald", 76, "MHKY", "Defense", "So", 5),
    p.player("Michael Outzen", 72, "MHKY", "Wing", "Sr", 7),
    p.player("Jackson Dorrington", 74, "MHKY", "Defense", "So", 8),
    p.player("Matt Choupani", 70, "MHKY", "Wing", "Jr", 9),
    p.player("Patrick Dawson", 72, "MHKY", "Defense", "Sr", 10),
    p.player("Gunnarwolfe Fontaine", 70, "MHKY", "Wing", "Sr", 11),
    p.player("Cam Lund", 74, "MHKY", "Wing", "So", 12),
    p.player("Liam Walsh", 73, "MHKY", "Center", "Sr", 14),
    p.player("Jack Williams", 71, "MHKY", "Center", "So", 15),
    p.player("Michael Fisher", 75, "MHKY", "Wing", "Fr", 16),
    p.player("Braden Doyle", 72, "MHKY", "Defense", "Jr", 17),
    p.player("Andy Moore", 71, "MHKY", "Wing", "Fr", 18),
    p.player("Billy Norcross", 72, "MHKY", "Wing", "Fr", 19),
    p.player("Brett Edwards", 70, "MHKY", "Wing", "Sr", 20),
    p.player("Matt DeMelis", 72, "MHKY", "Center", "Sr", 21),
    p.player("Vinny Borgesi", 68, "MHKY", "Defense", "So", 22),
    p.player("Eli Sebastian", 71, "MHKY", "Center ", "Fr", 23),
    p.player("Kyle Furey", 72, "MHKY", "Defense", "So", 24),
    p.player("Matthew Staudacher", 74, "MHKY", "Defense", "Sr", 25),
    p.player("Alex Campbell", 71, "MHKY", "Wing", "Sr", 27),
    p.player("Anthony Messuri", 68, "MHKY", "Wing", "So", 28),
    p.player("Justin Hryckowian", 70, "MHKY", "Center", "Jr", 29),
    p.player("Harrison Chesney", 74, "MHKY", "Goaltender", "So", 35),
    p.player("Grant Riley", 76, "MHKY", "Goaltender", "So", 37),
    p.player("Cameron Whitehead", 75, "MHKY", "Goaltender", "Fr", 39),

    p.player("Danny Crossen", 72, "Baseball", "UTL", "Sr", 1),
    p.player("Hayden Smith", 75, "Baseball", "RHP", "So", 2),
    p.player("Jack Thorbahn", 75, "Baseball", "INF", "Jr", 3),
    p.player("Dennis Colleran", 75, "Baseball", "RHP", "Jr", 4),
    p.player("Sean McGee", 73, "Baseball", "INF", "Fr", 5),
    p.player("Aiven Cabral", 71, "Baseball", "RHP", "Fr", 6),
    p.player("Cam Maldonado", 75, "Baseball", "OF", "Fr", 7),
    p.player("Mike Sirota", 74, "Baseball", "OF", "So", 8),
    p.player("Harrison Feinberg", 73, "Baseball", "OF", "So", 9),
    p.player("Alex Lane", 77, "Baseball", "OF", "Sr", 10),
    p.player("Eric Yost", 73, "Baseball", "RHP", "Jr", 11),
    p.player("Joseph Hauser", 75, "Baseball", "RHP", "Fr", 12),
    p.player("Matt Brinker", 70, "Baseball", "Catcher", "Fr", 13),
    p.player("Patrick Harrington", 73, "Baseball", "RHP", "Sr", 14),
    p.player("Matt Downing", 74, "Baseball", "LHP", "Jr", 15),
    p.player("Ryan Griffin", 78, "Baseball", "RHP", "Fr", 16),
    p.player("Brett Dunham", 74, "Baseball", "RHP", "So", 17),
    p.player("Griffin Young", 76, "Baseball", "RHP", "Sr", 18),
    p.player("Luke Beckstein", 67, "Baseball", "INF", "Jr", 19),
    p.player("Jordy Allard", 69, "Baseball", "RHP", "Sr", 20),
    p.player("Justin Bosland", 77, "Baseball", "UTL", "So", 21),
    p.player("Spenser Smith", 74, "Baseball", "INF", "Sr", 22),
    p.player("Ed Jarvis", 71, "Baseball", "Catcher", "Jr", 24),
    p.player("Craig Ottaviano", 77, "Baseball", "RHP", "Fr", 25),
    p.player("Jack Doyle", 72, "Baseball", "INF", "So", 27),
    p.player("Melo Musacchia", 72, "Baseball", "INF", "Fr", 28),
    p.player("Michael Gemma", 77, "Baseball", "RHP", "Jr", 31),
    p.player("James Quinlivan", 78, "Baseball", "LHP", "Jr", 32),
    p.player("Tyler MacGregor", 73, "Baseball", "INF", "Sr", 33),
    p.player("Luke Masiuk", 73, "Baseball", "OF", "So", 34),
    p.player("Jack Beauchesne", 74, "Baseball", "RHP", "So", 35),
    p.player("Nick Davis", 77, "Baseball", "RHP", "Sr", 36),
    p.player("Jake Gigliotti", 73, "Baseball", "RHP", "Jr", 37),
    p.player("Sean Quinlivan", 73, "Baseball", "RHP", "So", 39),
    p.player("Carson Walsh", 72, "Baseball", "RHP", "So", 43),
    p.player("Jimmy Sullivan", 72, "Baseball", "Catcher", "Fr", 45),
    p.player("Will Jones", 77, "Baseball", "LHP", "Jr", 45),
    p.player("Wyatt Scotti", 75, "Baseball", "RHP", "Jr", 46),
    p.player("James Morice", 77, "Baseball", "RHP", "Fr", 47),
    p.player("Gregory Bozzo", 72, "Baseball", "Catcher", "Jr", 49),

    p.player("Tyson Walker", 72, "MBB", "Guard", "Sr", 2)
]